//////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2021 Vladislav Fedotov (Falldot)
// License: MIT License
// MIT License web page: https://opensource.org/licenses/MIT
//
//////////////////////////////////////////////////////////////////////////
//
// This file generated by Entitas-Go generator. PLEASE DO NOT EDIT IT.
//
// Entitas-Go: github.com/Falldot/Entitas-Go
//
//////////////////////////////////////////////////////////////////////////
package ecs

const (
	Game = iota

//NEXT2
)

func CreateContexts() Contexts {
	return SetContexts(
		CreateEntityBase(GameComponentTotal),
	//NEXT2
	)
}
func (c *Contexts) Game() EntityBase {
	return (*c)[Game].(EntityBase)
}
